version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast-api:0.0.1
    env_file: .env
    restart: unless-stopped
    tty: true
    working_dir: /home/tuandc
    ports:
      - "8000:8000"
    networks:
      - app-networks
    volumes:
#      - ~/Dropbox/py-practice/fast-api-sv/app:/home/tuandc/app
#      - ~/Dropbox/py-practice/fast-api-sv/fast_api_app:/home/tuandc/fast_api_app
      - /Users/tuan.dc/Dropbox/py-practice/fast-api-sv/app:/home/tuandc/app
      - /Users/tuan.dc/Dropbox/py-practice/fast-api-sv/fast_api_app:/home/tuandc/fast_api_app

#    extra_hosts:
#      - "urbox-hn-kafka-dev:10.130.216.219"

networks:
  app-networks:
    driver: bridge
