version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast-api:0.0.1
    env_file: .env
    restart: unless-stopped
    tty: true
    working_dir: /home/tuandc
    ports:
      - "8000:8000"
    networks:
      - app-networks
    volumes:
#      - ~/Dropbox/py-practice/fast-api-sv/app:/home/tuandc/app
#      - ~/Dropbox/py-practice/fast-api-sv/fast_api_app:/home/tuandc/fast_api_app
      - /Users/tuan.dc/Dropbox/py-practice/fast-api-sv/app:/home/tuandc/app
      - /Users/tuan.dc/Dropbox/py-practice/fast-api-sv/fast_api_app:/home/tuandc/fast_api_app
      - /Users/tuan.dc/Dropbox/py-practice/fast-api-sv/grpc_app:/home/tuandc/grpc_app
      - /Users/tuan.dc/Dropbox/py-practice/fast-api-sv/schemas:/home/tuandc/schemas

  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      # - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=boyhandsome
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - app-networks

networks:
  app-networks:
    name: app-networks

volumes:
  db:
    driver: local
